Recovery TotalSubsidy
Qitmeer/qitmeer pull request #367
Opened 2020-09-09 12:57 UTC by lochjin

2020-09-09 13:42 UTC, dindinw approved these changes
The 0.10 start to support the weight calculation which not compatible with 0.9.x network.

2020-09-09 13:47 UTC, dindinw requested changes
The CI test is failed, Please double check unit test.
--- FAIL: Test_CheckBlueAndMature (0.02s)
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x84067e]

2020-09-10 23:09 UTC, lochjin commented
> The CI test is failed, Please double check unit test.
> --- FAIL: Test_CheckBlueAndMature (0.02s)
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> panic: runtime error: invalid memory address or nil pointer dereference [recovered]
> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x60 pc=0x84067e]

c3c27e3

2020-09-13 22:34 UTC, dindinw approved these changes

2020-09-13 22:34 UTC, merged