Optimize p2p
Qitmeer/qitmeer pull request #409
Opened 2020-12-12 12:08 UTC by lochjin

2020-12-13 03:05 UTC, dindinw reviewed
Please use go1.3 std error and remove the dependency from `pkg/errors`
see https://blog.golang.org/go1.13-errors for details.

2020-12-13 12:26 UTC, lochjin commented
> Please use go1.3 std error and remove the dependency from `pkg/errors`
> see https://blog.golang.org/go1.13-errors for details.

https://github.com/Qitmeer/qitmeer/pull/409/commits/b54e97acc2ce8f28a07d9e0c6eca629b12d1660d

2020-12-14 01:15 UTC, dindinw requested changes
Please fix the build  `Errorf call has arguments but no formatting directives`,  BTW,  you might also execute a `gofmt` additionally  
```golang	
	return nil, fmt.Errorf("could not get multiaddr:w", err)
```

2020-12-14 05:02 UTC, dindinw commented on cmd/crawler/node/node.go
> +		return nil, fmt.Errorf("could not get multiaddr:w%", err)
typo here, should be `%w`

2020-12-14 09:14 UTC, dindinw approved these changes

2020-12-14 09:14 UTC, merged