add wallet rpc service
Qitmeer/qitmeer pull request #442
Opened 2021-03-13 16:15 UTC by jamesvan2019

2021-03-19 04:00 UTC, jamesvan2019 commented
Fixed these comments

2021-03-19 04:29 UTC, jamesvan2019 commented on .gitignore
> +go.sum
had already resoved

2021-03-19 04:29 UTC, jamesvan2019 commented on rpc/errors.go
> +// unable to decode supplied ChainParams, or an invalid number of parameters
resolved

2021-03-19 05:22 UTC, lochjin requested changes

2021-03-20 00:29 UTC, lochjin requested changes

2021-03-20 00:29 UTC, lochjin commented on rpc/watchconfirm.go
> +			if bc.CacheInvalidTx {
Your purpose is just to confirm the transaction, why not `continue` directly?  I don't think it's necessary to deal with all the illegal transactions.

2021-03-20 00:29 UTC, lochjin commented on rpc/watchconfirm.go
> +		mtx.IsDuplicate = bc.IsDuplicateTx(mtx.Hash(), blockRegion.Hash)
```
if mtx.IsDuplicate {
   continue
}
```
why not `continue` directly? I don't think it's necessary to deal with all the illegal transactions.

2021-03-20 00:37 UTC, lochjin requested changes

2021-03-20 00:37 UTC, lochjin commented on rpc/watchconfirm.go
> +			isBlue = bc.BlockDAG().IsBlue(ib.GetID())
```
if isBlue {
   continue
}
```
The utxo of transaction in the red block  can't be spent, so there is no need to go on .

2021-03-20 00:37 UTC, lochjin commented on rpc/watchconfirm.go
> +				ConfirmResult: cmds.TxConfirmResult{
I think we just need one return value (`cmds.TxConfirmResult.Confirms`) for client.  Also, these parameters should have a priority: IsValid > IsBlue > Confirms,  so why don't we set illegal transactions as `cmds.TxConfirmResult.Confirms = 0` ?  . (We purpose is just to confirm the transaction.)

2021-03-20 06:21 UTC, lochjin approved these changes

2021-03-21 03:20 UTC, dindinw commented on rpc/client/cmds/jsonrpc.go
> +		Code:    -32604,
should follow http://xmlrpc-epi.sourceforge.net/specs/rfc.fault_codes.php and https://www.jsonrpc.org/specification 5.1 Error object

2021-03-21 03:34 UTC, dindinw approved these changes

2021-03-21 04:58 UTC, merged