Spv bloom filter
Qitmeer/qitmeer pull request #464
Opened 2021-04-05 16:34 UTC by jamesvan2019

2021-04-05 22:11 UTC, dindinw commented on common/bloom/filter_test.go
> +
why an empty test unit?

2021-04-05 22:11 UTC, dindinw commented on common/bloom/filter_test.go
> +
empty test unit

2021-04-05 22:15 UTC, dindinw requested changes
Please also add an integrated test for this feature, it's similar to the `WSNotifyTest` test.

2021-04-07 02:00 UTC, lochjin requested changes

2021-04-07 04:08 UTC, lochjin requested changes

2021-04-19 04:06 UTC, lochjin approved these changes

2021-04-19 04:10 UTC, lochjin approved these changes

2021-04-19 04:10 UTC, dindinw approved these changes

2021-04-19 04:12 UTC, dindinw commented
@jamesvan2019 the integrated test for SPV feature can be submit by a separated PR.

2021-04-19 04:19 UTC, merged