optimize qx tx-sign
Qitmeer/qitmeer pull request #679
Opened 2021-11-08 13:58 UTC by jamesvan2019

issue #553

2021-11-09 09:06 UTC, dindinw requested changes

2021-11-17 00:16 UTC, lochjin submitted a review, later dismissed

2021-11-17 00:16 UTC, lochjin commented on qx/handle_tx.go
>  	if len(rawTxStr)%2 != 0 {
Odd length hexadecimal string is very common, we just need to correct it automatically:
`
if len(rawTxStr)%2 != 0 {
	rawTxStr = "0" + rawTxStr
}
`

2021-11-20 01:29 UTC, dindinw commented
I believe you should always keep using separated branches for different tasks so that they have no affect with each other. Please clean up the irrelevant commits 656bd91 and cb76412 from this PR. @jamesvan2019

2021-11-30 07:21 UTC, dindinw approved these changes

2021-11-30 09:27 UTC, lochjin approved these changes

2021-11-30 09:30 UTC, merged